<?php

namespace Database\Seeders;

use App\Helpers\Model;
use App\Models\Release;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class ReleasesSeeder extends Seeder
{
    use Model;
    public function run()
    {
          $users = User::get();
          foreach($users as $user){
            foreach(self::descriptions() as $description){
                self::setData([
                    'description' => $description,
                    'value' => fake()->randomFloat(2,10,1500),
                    'date' => fake()->date(),
                    'status_pay' => Arr::random(['QUITADO','ABERTO']),
                    'type' => Arr::random(['ENTRADA','SAIDA']),
                    'user_id' => $user->id,
                    'category_id' => Arr::random($user->categories->pluck('id')->toArray()),
                    'payment_id' => Arr::random($user->payments->pluck('id')->toArray()),
                ],Release::class);
            }
          }

    }

    private static function descriptions(){
        return  [
            "Salário",
            "Aluguel Residencial",
            "Aluguel Comercial",
            "Hipoteca",
            "Conta de Luz",
            "Conta de Água",
            "Gás",
            "Internet",
            "TV a Cabo",
            "Telefone",
            "Supermercado",
            "Restaurante",
            "Café/Comida Rápida",
            "Delivery",
            "Roupas e Acessórios",
            "Calçados",
            "Farmácia",
            "Gastos com Saúde",
            "Academia",
            "Seguro Saúde",
            "Impostos",
            "Taxa de Condomínio",
            "Manutenção de Veículo",
            "Combustível",
            "Transporte Público",
            "Uber/Táxi",
            "Estacionamento",
            "Manutenção Residencial",
            "Serviços de Limpeza",
            "Assinatura de Jornal/Revista",
            "Lazer e Entretenimento",
            "Cinema/Teatro",
            "Assinatura de Streaming",
            "Viagens",
            "Presentes",
            "Doações",
            "Educação",
            "Cursos",
            "Livros",
            "Materiais de Escritório",
            "Hobbies",
            "Eletrônicos",
            "Gastos com Animais de Estimação",
            "Cuidados Pessoais",
            "Cabeleireiro/Barbeiro",
            "Produtos de Beleza",
            "Spa/Salão de Beleza",
            "Casamento",
            "Eventos Sociais",
            "Taxa Bancária",
            "Tarifa de Cartão de Crédito",
            "Transferências Bancárias",
            "Juros e Multas",
            "Investimentos",
            "Compra de Ações",
            "Fundos de Investimento",
            "Renda Fixa",
            "Pagamento de Empréstimo",
            "Reembolso",
            "Receitas Extras",
            "Freelance",
            "Venda de Itens Usados",
            "Prêmios e Loterias",
            "Bônus no Trabalho",
            "Restituição de Impostos",
            "Mesada",
            "Economias",
            "Transferência entre Contas",
            "Compra de Criptomoedas",
            "Pagamento de Faturas",
            "Mensalidade de Serviços",
            "Aluguel de Equipamentos",
            "Despesas Governamentais",
            "Taxa Ambiental",
            "Eventos Esportivos",
            "Patrocínio",
            "Consultoria Financeira",
            "Manutenção de Computadores",
            "Comissões e Taxas",
            "Compras Online",
            "Compras em Lojas Físicas",
            "Mudança Residencial",
            "Despesas de Mudança",
            "Manutenção de Jardim",
            "Material de Construção",
            "Pagamento de Advogado",
            "Despesas com Caridade",
            "Assinatura de Aplicativos",
            "Comida para Viagem",
            "Móveis e Decoração",
            "Equipamentos de Escritório",
            "Serviços de Consultoria",
            "Treinamentos",
            "Desenvolvimento Profissional",
            "Manutenção de Equipamentos",
            "Equipamentos de Lazer",
            "Assinatura de Cursos Online",
            "Assinatura de Software",
            "Despesas com Filhos",
            "Educação Infantil",
            "Despesas com Crianças",
            "Produtos para Bebê",
            "Despesas com Adolescentes",
            "Gastos com Faculdade",
            "Jogos e Brinquedos",
            "Despesas com a Casa dos Pais",
            "Assistência Técnica",
            "Materiais para Artes e Artesanato",
            "Assinatura de Clubes",
            "Café da Manhã/Padaria",
            "Tutoriais Online",
            "Desenvolvimento Pessoal",
            "Assinatura de Apresentações",
            "Despesas com Podcasts",
            "Despesas com Música",
            "Despesas com Arte",
            "Cuidados com a Saúde Mental",
            "Terapia",
            "Cursos de Idiomas",
            "Roupas de Dormir",
            "Assinatura de Quadrinhos",
            "Despesas com Tecnologia",
            "Assinatura de Antivírus",
            "Manutenção de Dispositivos Eletrônicos",
            "Assinatura de Backup Online",
            "Gastos com Redes Sociais",
            "Assinatura de VPN",
            "Assinatura de Armazenamento na Nuvem",
            "Gastos com Energia Solar",
            "Despesas de Marketing",
            "Publicidade Online",
            "Marketing de Conteúdo",
            "Despesas com Freelancers",
            "Patrocínio de Eventos",
            "Equipamentos de Filmagem",
            'Aluguel',
            'Hypoteca',
            'Seguro de vida',
            'Seguro de saúde',
            'Seguro de automóvel',
            'Imposto de renda',
            'Manutenção da casa',
            'Reparos elétricos',
            'Reparos hidráulicos',
            'Limpeza da casa',
            'Produtos de limpeza',
            'Material de escritório',
            'Material de jardinagem',
            'Supermercado',
            'Mercado online',
            'Feira (frutas e verduras)',
            'Padaria',
            'Açougue',
            'Restaurante',
            'Delivery de comida',
            'Lanches',
            'Café da manhã fora de casa',
            'Almoço fora de casa',
            'Jantar fora de casa',
            'Café',
            'Chá',
            'Água mineral',
            'Bebidas alcoólicas',
            'Farmácia',
            'Medicamentos prescritos',
            'Vitaminas',
            'Produtos de beleza',
            'Cabelereiro/barbeiro',
            'Roupas',
            'Calçados',
            'Acessórios',
            'Roupas íntimas',
            'Lavanderia',
            'Material de limpeza pessoal',
            'Assinaturas (Netflix, Spotify, etc.)',
            'Academia',
            'Esportes',
            'Equipamentos esportivos',
            'Cinema',
            'Teatro',
            'Shows',
            'Eventos esportivos',
            'Viagens',
            'Hospedagem',
            'Passagens aéreas',
            'Transporte público',
            'Combustível',
            'Manutenção do carro',
            'Estacionamento',
            'Táxi/Uber/Lyft',
            'Assistência técnica de eletrônicos',
            'Eletrônicos',
            'Computador',
            'Smartphone',
            'Tablet',
            'Impressora',
            'Games',
            'Livros',
            'Revistas',
            'Jornais',
            'Material escolar',
            'Cursos online',
            'Assinaturas de software',
            'Contribuições de caridade',
            'Presentes',
            'Festas de aniversário',
            'Eventos especiais',
            'Decoração de casa',
            'Móveis',
            'Utensílios de cozinha',
            'Roupas de cama',
            'Toalhas',
            'Eletrodomésticos',
            'Ferramentas',
            'Materiais de construção',
            'Condomínio',
            'Taxas bancárias',
            'Empréstimos',
            'Cartão de crédito',
            'Investimentos',
            'Educação',
            'Mensalidade escolar',
            'Material escolar',
            'Faculdade/universidade',
            'Cursos adicionais',
            'Seguro educacional',
            'Serviços de saúde',
            'Consultas médicas',
            'Exames',
            'Odontologia',
            'Óculos/lentes de contato',
            'Cuidados com animais de estimação',
            'Ração',
            'Produtos de cuidado',
            'Consulta veterinária',
            'Pet-sitter',
            'Segurança',
            'Câmeras de segurança',
            'Sistema de alarme',
            'Segurança do bairro',
            'Hobbies',
            'Instrumentos musicais',
            'Material de arte',
            'Equipamento esportivo',
            'Jogos de tabuleiro',
            'Assinaturas de streaming de música',
            'Eventos esportivos',
            'Passatempos específicos (modelismo, colecionismo, etc.)',
            'Serviços de streaming',
            'Netflix',
            'Hulu',
            'Amazon Prime Video',
            'Disney+',
            'Spotify',
            'Apple Music',
            'Amazon Music',
            'Outros serviços específicos',
            'Aulas particulares',
            'Equipamentos de jardinagem',
            'Comida para animais de estimação',
            'Conserto de eletrodomésticos',
            'Cafeteira',
            'Ferro de passar roupa',
            'Aspirador de pó',
            'Máquina de lavar louça',
            'Secadora de roupas',
            'Máquina de lavar roupa',
            'Aquecedor',
            'Ar-condicionado',
            'Ventilador',
            'Despesas bancárias',
            'Tarifas de caixa eletrônico',
            'Taxa de transferência',
            'Tarifa mensal do banco',
            'Empréstimos pessoais',
            'Pagamento mínimo do cartão de crédito',
            'Taxas de cartão de crédito',
            'Investimento em ações',
            'Investimento em criptomoedas',
            'Aplicativos de produtividade',
            'Aplicativos de organização',
            'Softwares de segurança',
            'Aplicativos de edição de fotos',
            'Assinatura de revistas online',
            'Assinatura de jornais digitais',
            'Assinatura de revistas impressas',
            'Planos de telefonia móvel',
            'Planos de internet fixa',
            'Mensalidade de cursos presenciais',
            'Livros didáticos',
            'Equipamentos esportivos',
            'Mensalidade de clube social',
            'Assinatura de revistas de moda',
            'Despesas com energia solar',
            'Aulas de música',
            'Aulas de dança',
            'Aulas de idiomas',
            'Taxas de visto',
            'Despesas com transporte escolar',
            'Assinatura de aplicativos de aprendizado',
            'Equipamentos de camping',
            'Despesas com home office',
            'Freelancers',
            'Despesas com coworking',
            'Manutenção de piscina',
            'Associação de bairro',
            'Despesas com jardinagem',
            'Equipamentos de pesca',
            'Licença de pesca',
            'Cuidados com plantas',
            'Despesas com horta caseira',
            'Despesas com impressão',
            'Aluguel de equipamentos esportivos',
            'Despesas com alimentos orgânicos',
            'Assinatura de revistas científicas',
            'Despesas com feriados',
            'Assinatura de sites de notícias',
            'Seguro contra inundação',
            'Manutenção de barco',
            'Despesas com barco',
            'Manutenção de bicicleta',
            'Despesas com bicicleta',
            'Aulas de ioga',
            'Aulas de pilates',
            'Equipamentos de esportes aquáticos',
            'Assinatura de revistas de culinária',
            'Despesas com hobbies criativos',
            'Despesas com hobbies tecnológicos',
            'Assinatura de sites de pesquisa acadêmica',
            'Despesas com eletrodomésticos inteligentes',
            'Assinatura de serviços de consultoria',
            'Equipamentos de fotografia',
            'Despesas com fotografias profissionais',
            'Assinatura de aplicativos de meditação',
            'Equipamentos de acampamento',
            'Despesas com hobbies ao ar livre',
            'Assinatura de serviços de entrega de alimentos',
            'Assinatura de serviços de streaming de esportes',
            'Despesas com eventos esportivos ao vivo',
            'Despesas com produtos sustentáveis',
            'Assinatura de serviços de receitas culinárias',
            'Despesas com workshops e cursos online',
            'Assinatura de serviços de audiobooks',
            'Despesas com materiais de artesanato',
            'Assinatura de serviços de cloud computing',
            'Equipamentos de realidade virtual',
            'Despesas com experiências culturais',
            'Assinatura de serviços de aprendizado de idiomas',
            'Despesas com cursos de marketing digital',
            'Assinatura de serviços de design gráfico',
            'Despesas com serviços de impressão 3D',
            'Assinatura de serviços de programação',
            'Equipamentos de realidade aumentada',
            'Despesas com aulas de ciências',
            'Assinatura de serviços de análise de dados',
            'Despesas com aulas de história',
            'Assinatura de serviços de edição de vídeo',
            'Despesas com aulas de geografia',
            'Assinatura de serviços de música clássica',
            'Despesas com aulas de matemática',
            'Assinatura de serviços de música eletrônica',
            'Despesas com aulas de literatura',
            'Assinatura de serviços de música indie',
            'Despesas com aulas de idiomas estrangeiros',
            'Assinatura de serviços de música pop',
            'Despesas com aulas de arte',
            'Assinatura de serviços de música rock',
            'Despesas com aulas de música',
            'Assinatura de serviços de música hip-hop',
            'Despesas com aulas de teatro',
            'Assinatura de serviços de música country',
            'Despesas com aulas de dança',
            'Assinatura de serviços de música jazz',
            'Despesas com aulas de culinária',
            'Assinatura de serviços de música blues',
            'Despesas com aulas de fotografia',
            'Assinatura de serviços de música clássica indiana',
            'Despesas com aulas de jardinagem',
            'Assinatura de serviços de música latina',
            'Despesas com aulas de costura',
            'Assinatura de serviços de música ambiental',
            'Despesas com aulas de programação',
            'Assinatura de serviços de música gospel',
            'Despesas com aulas de design gráfico',
            'Assinatura de serviços de música reggae',
            'Despesas com aulas de marketing digital',
            'Assinatura de serviços de música metal',
            'Despesas com aulas de desenvolvimento web',
            'Assinatura de serviços de música punk',
            'Despesas com aulas de redação',
            'Assinatura de serviços de música R&B',
            'Despesas com aulas de comunicação',
            'Assinatura de serviços de música techno',
            'Despesas com aulas de psicologia',
            'Assinatura de serviços de música indie pop',
            'Despesas com aulas de ciência da computação',
            'Assinatura de serviços de música eletrônica',
            'Despesas com aulas de finanças pessoais',
            'Assinatura de serviços de música pop rock',
            'Despesas com aulas de gestão de tempo',
            'Assinatura de serviços de música soul',
            'Despesas com aulas de habilidades interpessoais',
            'Assinatura de serviços de música country rock',
            'Despesas com aulas de liderança',
            'Assinatura de serviços de música blues rock',
            'Despesas com aulas de negociação',
            'Assinatura de serviços de música jazz fusion',
            'Despesas com aulas de empreendedorismo',
            'Assinatura de serviços de música hip-hop soul',
            'Despesas com aulas de produtividade',
            'Assinatura de serviços de música bluegrass',
            'Despesas com aulas de resolução de conflitos',
            'Assinatura de serviços de música instrumental',
            'Despesas com aulas de comunicação eficaz',
            'Assinatura de serviços de música ambiental',
            'Despesas com aulas de criatividade',
            'Assinatura de serviços de música acústica',
            'Despesas com aulas de ética',
            'Assinatura de serviços de música reggaeton',
            'Despesas com aulas de design thinking',
            'Assinatura de serviços de música pop latino',
            'Despesas com aulas de marketing',
            'Assinatura de serviços de música latina pop',
            'Despesas com aulas de gestão de projetos',
            'Assinatura de serviços de música rap',
            'Despesas com aulas de publicidade',
            'Assinatura de serviços de música gospel',
            'Despesas com aulas de relações públicas',
            'Assinatura de serviços de música funk',
            'Despesas com aulas de mídias sociais',
            'Assinatura de serviços de música country pop',
            'Despesas com aulas de branding',
            'Assinatura de serviços de música rock alternativo',
            'Despesas com aulas de SEO',
            'Assinatura de serviços de música indie rock',
            'Despesas com aulas de e-mail marketing',
            'Assinatura de serviços de música punk rock',
            'Despesas com aulas de marketing de conteúdo',
            'Assinatura de serviços de música R&B contemporâneo',
            'Despesas com aulas de storytelling',
            'Assinatura de serviços de música techno pop',
            'Despesas com aulas de design de interface',
            'Assinatura de serviços de música pop eletrônico',
            'Despesas com aulas de desenvolvimento pessoal',
            'Assinatura de serviços de música dance pop',
            'Despesas com aulas de coaching',
            'Aluguel',
            'Hypoteca',
            'Conta de luz',
            'Conta de água',
            'Internet',
            'Telefone fixo',
            'Telefone celular',
            'TV a cabo/satélite',
            'Seguro residencial',
            'Seguro de vida',
            'Seguro de saúde',
            'Seguro de automóvel',
            'Impostos municipais',
            'Impostos estaduais',
            'Imposto de renda',
            'Manutenção da casa',
            'Reparos elétricos',
            'Reparos hidráulicos',
            'Manutenção do jardim',
            'Limpeza da casa',
            'Produtos de limpeza',
            'Material de escritório',
            'Material de jardinagem',
            'Supermercado',
            'Mercado online',
            'Feira (frutas e verduras)',
            'Padaria',
            'Açougue',
            'Restaurante',
            'Delivery de comida',
            'Lanches',
            'Café da manhã fora de casa',
            'Almoço fora de casa',
            'Jantar fora de casa',
            'Café',
            'Chá',
            'Água mineral',
            'Bebidas alcoólicas',
            'Farmácia',
            'Medicamentos prescritos',
            'Vitaminas',
            'Produtos de beleza',
            'Cabelereiro/barbeiro',
            'Roupas',
            'Calçados',
            'Acessórios',
            'Roupas íntimas',
            'Lavanderia',
            'Material de limpeza pessoal',
            'Assinaturas (Netflix, Spotify, etc.)',
            'Academia',
            'Esportes',
            'Equipamentos esportivos',
            'Cinema',
            'Teatro',
            'Shows',
            'Eventos esportivos',
            'Viagens',
            'Hospedagem',
            'Passagens aéreas',
            'Transporte público',
            'Combustível',
            'Manutenção do carro',
            'Estacionamento',
            'Táxi/Uber/Lyft',
            'Assistência técnica de eletrônicos',
            'Eletrônicos',
            'Computador',
            'Smartphone',
            'Tablet',
            'Impressora',
            'Games',
            'Livros',
            'Revistas',
            'Jornais',
            'Material escolar',
            'Cursos online',
            'Assinaturas de software',
            'Contribuições de caridade',
            'Presentes',
            'Festas de aniversário',
            'Eventos especiais',
            'Decoração de casa',
            'Móveis',
            'Utensílios de cozinha',
            'Roupas de cama',
            'Toalhas',
            'Eletrodomésticos',
            'Ferramentas',
            'Materiais de construção',
            'Condomínio',
            'Taxas bancárias',
            'Empréstimos',
            'Cartão de crédito',
            'Investimentos',
            'Educação',
            'Mensalidade escolar',
            'Material escolar',
            'Faculdade/universidade',
            'Cursos adicionais',
            'Seguro educacional',
            'Consultas médicas',
            'Exames',
            'Odontologia',
            'Óculos/lentes de contato',
            'Cuidados com animais de estimação',
            'Ração',
            'Produtos de cuidado',
            'Consulta veterinária',
            'Pet-sitter',
            'Segurança',
            'Câmeras de segurança',
            'Sistema de alarme',
            'Segurança do bairro',
            'Hobbies',
            'Instrumentos musicais',
            'Material de arte',
            'Equipamento esportivo',
            'Jogos de tabuleiro',
            'Assinaturas de streaming de música',
            'Eventos esportivos',
            'Passatempos específicos (modelismo, colecionismo, etc.)',
            'Serviços de streaming',
            'Netflix',
            'Hulu',
            'Amazon Prime Video',
            'Disney+',
            'Spotify',
            'Apple Music',
            'Amazon Music',
            'Outros serviços específicos',
            'Despesas veterinárias',
            'Despesas com festas',
            'Despesas com viagens de lazer',
            'Taxas de câmbio',
            'Despesas com entretenimento',
            'Despesas com eletrodomésticos',
            'Assinaturas de revistas',
            'Despesas com jardinagem',
            'Manutenção de piscina',
            'Despesas com esportes aquáticos',
            'Despesas com brinquedos',
            'Despesas com eletricista',
            'Despesas com encanador',
            'Despesas com arquiteto',
            'Despesas com pedreiro',
            'Despesas com mudanças',
            'Despesas com terapeuta',
            'Despesas com psicólogo',
            'Despesas com acupuntura',
            'Despesas com massagem',
            'Despesas com spa',
            'Despesas com tratamentos estéticos',
            'Despesas com cabeleireiro',
            'Despesas com manicure/pedicure',
            'Despesas com joias',
            'Despesas com hobbies',
            'Despesas com impressões',
            'Despesas com aluguel de filmes',
            'Despesas com concertos',
            'Despesas com festivais',
            'Despesas com eventos esportivos ao vivo',
            'Despesas com material de pesca',
            'Despesas com camping',
            'Despesas com arte',
            'Despesas com fotografias',
            'Despesas com museus',
            'Despesas com parques de diversão',
            'Despesas com feriados',
            'Despesas com bricolagem',
            'Despesas com artigos de couro',
            'Despesas com antiguidades',
            'Despesas com caridade',
            'Despesas com presentes de última hora',
            'Despesas com armazenamento',
            'Despesas com organização',
            'Despesas com aplicativos móveis',
            'Despesas com aulas particulares',
            'Despesas com apostas',
            'Despesas com clubes sociais',
            'Despesas com ações e investimentos',
            'Despesas com impostos sobre investimentos',
            'Despesas com taxas de corretagem',
            'Despesas com artigos esportivos',
            'Despesas com bicicletas',
            'Despesas com corridas e maratonas',
            'Despesas com camping',
            'Despesas com passeios de barco',
            'Despesas com golfe',
            'Despesas com tênis',
            'Despesas com equipamentos de camping',
            'Despesas com pesca',
            'Despesas com mergulho',
            'Despesas com esqui',
            'Despesas com snowboard',
            'Despesas com patinação',
            'Despesas com esportes radicais',
            'Despesas com equipamentos de pesca',
            'Despesas com artes marciais',
            'Despesas com equipamentos de golfe',
            'Despesas com artigos de pesca',
            'Despesas com artigos de mergulho',
            'Despesas com artigos de esqui',
            'Despesas com artigos de snowboard',
            'Despesas com artigos de patinação',
            'Despesas com artigos de esportes radicais',
            'Despesas com equipamentos de artes marciais',
            'Despesas com equipamentos de golfe',
            'Despesas com equipamentos esportivos diversos',
            'Despesas com óculos de sol',
            'Despesas com bolas e acessórios esportivos',
            'Despesas com acessórios de ciclismo',
            'Despesas com tênis esportivos',
            'Despesas com joelheiras e cotoveleiras',
            'Despesas com suplementos alimentares',
            'Despesas com academias online',
            'Despesas com personal trainer',
            'Despesas com aulas de ioga',
            'Despesas com aulas de pilates',
            'Despesas com esportes aquáticos',
            'Despesas com aulas de natação',
            'Despesas com esportes de equipe',
            'Despesas com aulas de dança',
            'Despesas com aulas de música',
            'Despesas com equipamentos de música',
            'Despesas com concertos e shows musicais',
            'Despesas com instrumentos musicais',
            'Despesas com aulas de arte',
            'Despesas com materiais de arte',
            'Despesas com cursos de arte',
            'Despesas com obras de arte',
            'Despesas com festivais de arte',
            'Despesas com artigos de escrita',
            'Despesas com livros de arte',
            'Despesas com cursos online de arte',
            'Despesas com instrumentos de escrita',
            'Despesas com material de escrita',
            'Despesas com penas e tintas',
            'Despesas com papelaria',
            'Despesas com cadernos e agendas',
            'Despesas com acessórios de escritório',
            'Despesas com móveis de escritório',
            'Despesas com iluminação de escritório',
            'Despesas com decoração de escritório',
            'Despesas com eletrônicos de escritório',
            'Despesas com materiais de organização',
            'Despesas com serviços de organização',
            'Despesas com utensílios de cozinha',
            'Despesas com eletrodomésticos de cozinha',
            'Despesas com panelas e frigideiras',
            'Despesas com utensílios para assar',
            'Despesas com acessórios para cozinha',
            'Despesas com toalhas de cozinha',
            'Despesas com roupa de cama',
            'Despesas com roupa de banho',
            'Despesas com cortinas e persianas',
            'Despesas com tapetes e carpetes',
            'Despesas com móveis de quarto',
            'Despesas com colchões e travesseiros',
            'Despesas com iluminação de quarto',
            'Despesas com decoração de quarto',
            'Despesas com eletrônicos de quarto',
            'Despesas com artigos de banheiro',
            'Despesas com produtos de higiene pessoal',
            'Despesas com toalhas de banho',
            'Despesas com produtos de cuidado pessoal',
            'Despesas com acessórios de banheiro',
            'Despesas com roupas de banho',
            'Despesas com equipamentos de jardinagem',
            'Despesas com ferramentas de jardinagem',
            'Despesas com plantas e flores',
            'Despesas com adubos e fertilizantes',
            'Despesas com acessórios de jardinagem',
            'Despesas com serviços de jardinagem',
            'Despesas com manutenção de piscina',
            'Despesas com produtos para piscina',
            'Despesas com equipamentos de piscina',
            'Despesas com brinquedos para piscina',
            'Despesas com jogos de piscina',
            'Despesas com roupas infantis',
            'Despesas com calçados infantis',
            'Despesas com brinquedos infantis',
            'Despesas com material escolar',
            'Despesas com uniformes escolares',
            'Despesas com livros didáticos',
            'Despesas com mensalidades escolares',
            'Despesas com cursos extracurriculares',
            'Despesas com material de arte escolar',
            'Despesas com transporte escolar',
            'Despesas com festas e eventos escolares',
            'Despesas com artigos de papelaria',
            'Despesas com lanches escolares',
            'Despesas com cuidados com animais de estimação',
            'Despesas com ração',
            'Despesas com petiscos',
            'Despesas com brinquedos para animais',
            'Despesas com camas e casinhas',
            'Despesas com coleiras e guias',
            'Despesas com produtos de higiene animal',
            'Despesas com serviços de pet-sitter',
            'Despesas com veterinário',
            'Despesas com vacinas e check-ups',
            'Despesas com medicamentos para animais',
            'Despesas com treinamento e adestramento',
            'Despesas com roupas e acessórios para animais',
            'Despesas com seguros para animais de estimação',
            'Despesas com impostos e licenças para animais',
            'Despesas com produtos de limpeza para animais',
            'Despesas com equipamentos e brinquedos para treino',
            'Aluguel',
            'Assinatura de streaming (Netflix, Hulu, etc.)',
            'Conta de energia elétrica',
            'Plano de celular',
            'Seguro de vida',
            'Imposto de renda',
            'Supermercado',
            'Gás',
            'Internet',
            'Manutenção do carro',
            'Assinatura de revistas',
            'Despesas com animais de estimação',
            'Café da manhã fora de casa',
            'Roupas',
            'Calçados',
            'Academia',
            'Cinema',
            'Material escolar',
            'Medicamentos',
            'Produtos de limpeza',
            'Assinatura de jornal',
            'Conta de água',
            'Telefone fixo',
            'Impostos municipais',
            'Taxa de condomínio',
            'Seguro de saúde',
            'Assinatura de software',
            'Reparos na casa',
            'Manutenção de jardim',
            'Refeições em restaurantes',
            'Luz',
            'Telefone celular',
            'Seguro do carro',
            'Internet móvel',
            'Cursos online',
            'Presentes',
            'Eletrônicos',
            'Roupa de cama',
            'Artigos de decoração',
            'Ferramentas',
            'Taxa bancária',
            'Almoço fora de casa',
            'Flores e plantas',
            'Manicure/pedicure',
            'Festas e eventos',
            'Lavanderia',
            'Material de escritório',
            'Viagens',
            'Taxa de estacionamento',
            'Hobbies',
            'Esportes',
            'Segurança residencial',
            'Óculos e lentes de contato',
            'Beleza e cuidados pessoais',
            'Taxa de internet',
            'Concertos e shows',
            'Material de arte',
            'Equipamento esportivo',
            'Aluguel de filmes',
            'Café',
            'Chá',
            'Artigos de papelaria',
            'Taxa de cartão de crédito',
            'Seguro de residência',
            'Produtos de beleza',
            'Seguro de viagem',
            'Assinatura de ginásio',
            'Joias',
            'Despesas com caridade',
            'Aluguel de equipamentos esportivos',
            'Assinatura de aplicativos móveis',
            'Flores e presentes',
            'Despesas com festas',
            'Roupas íntimas',
            'Festival de comida',
            'Despesas com o carro',
            'Aluguel de bicicletas',
            'Despesas com transporte público',
            'Assistência técnica de eletrônicos',
            'Manutenção de computadores',
            'Concertos',
            'Instrumentos musicais',
            'Taxas de correio',
            'Despesas com arte digital',
            'Aulas particulares',
            'Conferências e eventos profissionais',
            'Assinatura de academia online',
            'Equipamento de camping',
            'Horticultura',
            'Piscina',
            'Assinatura de revista em quadrinhos',
            'Taxa de inscrição em eventos',
            'Assinatura de revista científica',
            'Equipamento de pesca',
            'Assinatura de plataforma de aprendizado online',
            'Despesas com impressões 3D',
            'Despesas com produtos ecológicos',
            'Assinatura de site de notícias',
            'Assinatura de serviço de entrega de alimentos',
            'Assinatura de serviço de streaming de música',
            'Assinatura de serviço de streaming de vídeo',
            'Assinatura de serviço de armazenamento em nuvem',
            'Assinatura de serviço de VPN',
            'Assinatura de serviço de jogos online',
            'Assinatura de serviço de audiobook',
            'Assinatura de serviço de podcast',
            'Assinatura de serviço de audiobook',
            'Despesas com cuidados com a pele',
            'Despesas com produtos de saúde e bem-estar',
            'Despesas com terapia física',
            'Despesas com terapia ocupacional',
            'Despesas com produtos de cuidados capilares',
            'Despesas com brinquedos e jogos',
            'Despesas com utensílios de cozinha',
            'Despesas com serviços de alimentação (por exemplo, refeições entregues)',
            'Despesas com organização doméstica',
            'Despesas com assinatura de serviço de armazenamento de fotos',
            'Despesas com assinatura de serviço de streaming de esportes',
            'Despesas com produtos de cuidado bucal',
            'Despesas com atividades ao ar livre',
            'Despesas com acessórios de moda',
            'Despesas com reparos de eletrônicos',
            'Despesas com reparos de eletrodomésticos',
            'Despesas com reparos de encanamento',
            'Despesas com reparos de construção',
            'Despesas com reparos de automóveis',
            'Despesas com reparos de computadores',
            'Despesas com reparos de móveis',
            'Despesas com reparos de roupas',
            'Despesas com reparos de calçados',
            'Despesas com reparos de joias',
            'Despesas com reparos de instrumentos musicais',
            'Despesas com reparos de utensílios de cozinha',
            'Despesas com reparos de brinquedos',
            'Despesas com reparos de jogos',
            'Despesas com reparos de equipamentos esportivos',
            'Despesas com reparos de artigos de decoração',
            'Despesas com reparos de materiais de jardinagem',
            'Despesas com reparos de eletrônicos de entretenimento',
            'Despesas com reparos de dispositivos móveis',
            'Despesas com reparos de equipamentos esportivos aquáticos',
            'Despesas com reparos de equipamentos de camping',
            'Despesas com reparos de instrumentos musicais',
            'Despesas com reparos de eletrodomésticos de cozinha',
            'Despesas com reparos de equipamentos de fotografia',
            'Despesas com reparos de ferramentas',
            'Despesas com reparos de utensílios de cozinha',
            'Despesas com reparos de produtos de cuidado pessoal',
            'Despesas com reparos de brinquedos infantis',
            'Despesas com reparos de acessórios de moda',
            'Despesas com reparos de equipamentos de jardinagem',
            'Despesas com reparos de artigos de decoração',
            'Despesas com reparos de materiais de arte',
            'Despesas com reparos de equipamentos de esportes',
            'Despesas com reparos de roupas de cama',
            'Despesas com reparos de utensílios domésticos',
            'Despesas com reparos de ferramentas de jardinagem',
            'Despesas com reparos de brinquedos de jardim',
            'Despesas com reparos de instrumentos musicais de jardim',
            'Despesas com reparos de equipamentos de festa',
            'Despesas com reparos de acessórios de festa',
            'Despesas com reparos de brinquedos de festa',
            'Despesas com reparos de decorações de festa',
            'Despesas com reparos de jogos de festa',
            'Despesas com reparos de materiais de escritório',
            'Despesas com reparos de materiais de escola',
            'Despesas com reparos de materiais de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de escritório',
            'Despesas com reparos de material de escola',
            'Despesas com reparos de material de arte',
            'Despesas com reparos de material de jardinagem',
            'Despesas com reparos de material de esportes',
            'Despesas com reparos de material de camping',
            'Despesas com reparos de material de pesca',
            'Despesas com reparos de material de música',
            'Despesas com reparos de material de fotografia',
          ];
    }
}
